// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pingpong.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pingpong.proto

It has these top-level messages:
	Ping
	Pong
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ping struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ping) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Pong struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Pong) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Ping)(nil), "main.Ping")
	proto.RegisterType((*Pong)(nil), "main.Pong")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PingPong service

type PingPongClient interface {
	PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type pingPongClient struct {
	cc *grpc.ClientConn
}

func NewPingPongClient(cc *grpc.ClientConn) PingPongClient {
	return &pingPongClient{cc}
}

func (c *pingPongClient) PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := grpc.Invoke(ctx, "/main.PingPong/PingPong", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PingPong service

type PingPongServer interface {
	PingPong(context.Context, *Ping) (*Pong, error)
}

func RegisterPingPongServer(s *grpc.Server, srv PingPongServer) {
	s.RegisterService(&_PingPong_serviceDesc, srv)
}

func _PingPong_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.PingPong/PingPong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).PingPong(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingPong_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.PingPong",
	HandlerType: (*PingPongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingPong",
			Handler:    _PingPong_PingPong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pingpong.proto",
}

func init() { proto.RegisterFile("pingpong.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0xbd, 0xaa, 0xc2, 0x40,
	0x10, 0x46, 0x6f, 0x20, 0xdc, 0x9f, 0x2d, 0x6e, 0x91, 0x2a, 0x58, 0x85, 0x60, 0x61, 0x93, 0x5d,
	0xd1, 0x37, 0xb0, 0x10, 0x4b, 0xb1, 0xb4, 0x91, 0xcd, 0xb2, 0x8c, 0x8b, 0xd9, 0x99, 0x61, 0x7f,
	0xc0, 0xbc, 0xbd, 0x24, 0x10, 0xb0, 0xb2, 0x3b, 0x07, 0x0e, 0x33, 0x7c, 0xe2, 0x9f, 0x1d, 0x02,
	0x13, 0x82, 0xe4, 0x40, 0x89, 0xaa, 0xd2, 0x6b, 0x87, 0x6d, 0x23, 0xca, 0xb3, 0x43, 0xa8, 0x6a,
	0xf1, 0xe3, 0x6d, 0x8c, 0x1a, 0x6c, 0x5d, 0x34, 0xc5, 0xe6, 0xef, 0xb2, 0xe8, 0x5c, 0xd0, 0xa7,
	0x62, 0xb7, 0x15, 0xbf, 0xd3, 0x8d, 0xb9, 0x5a, 0xbf, 0xb1, 0x90, 0xd3, 0x0b, 0x39, 0xf9, 0x6a,
	0x61, 0x42, 0x68, 0xbf, 0x0e, 0xa7, 0xeb, 0x11, 0x5c, 0xba, 0xe7, 0x5e, 0x1a, 0xf2, 0x8a, 0x07,
	0x9d, 0x1c, 0x66, 0xef, 0x09, 0x1f, 0x76, 0x54, 0x40, 0x9d, 0x21, 0x34, 0x39, 0x04, 0x8b, 0x66,
	0xec, 0x06, 0xe7, 0x5d, 0x8a, 0xca, 0x3e, 0xb5, 0xe7, 0xc1, 0x46, 0x05, 0x81, 0xcd, 0x2d, 0xa3,
	0x0e, 0xa3, 0xe2, 0xbe, 0xff, 0x9e, 0xc7, 0xec, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x90,
	0xab, 0x49, 0xde, 0x00, 0x00, 0x00,
}
