name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff  # v5
      with:
        go-version-file: 'go.mod'
        cache: true
        cache-dependency-path: go.sum

    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go mod download

    # Run lint on the code
    - name: Lint
      uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa  # v7

    # Fmt and Vet
    - name: Fmt and Vet
      run: |
        go fmt ./...
        go vet ./...

    # Run testing on the code
    - name: Run testing
      run: go test -v -race -covermode=atomic -coverprofile=covprofile ./...

    # todo: fix coverage reports...
